# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='rpc.py',
    version='0.4.1',
    description='An fast and powerful RPC framework based on ASGI/WSGI.',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "homepage": "https://github.com/abersheeran/rpc.py",
        "repository": "https://github.com/abersheeran/rpc.py"
    },
    author='abersheeran',
    author_email='me@abersheeran.com',
    license='Apache-2.0',
    classifiers=[
        'Programming Language :: Python :: 3', 'Typing :: Typed',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: WSGI :: Application'
    ],
    packages=['rpcpy', 'rpcpy.utils'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'typing-extensions==3.*,>=3.7.4; python_version < "3.8"'],
    extras_require={
        "client": ["httpx==0.*,>=0.16.0"],
        "dev": [
            "black", "flake8", "mypy", "pytest==5.*,>=5.4.3",
            "pytest-asyncio==0.*,>=0.14.0"
        ],
        "full": [
            "httpx==0.*,>=0.16.0", "msgpack==1.*,>=1.0.0",
            "pydantic==1.*,>=1.6.1"
        ],
        "msgpack": ["msgpack==1.*,>=1.0.0"],
        "type": ["pydantic==1.*,>=1.6.1"]
    },
)
